name: build-rootfs

on: workflow_dispatch

jobs:
    build:
        runs-on: windows-2022
        steps:
            - name: checkout
              uses: actions/checkout@v2
            - name: convert shell scripts
              run: |
                  ((Get-Content scripts/postinstall.sh) -join "`n") + "`n" | Set-Content -NoNewline scripts/postinstall.sh
                  ((Get-Content scripts/userspace.sh) -join "`n") + "`n" | Set-Content -NoNewline scripts/userspace.sh
            - name: run build script
              run: scripts/build.cmd
            - name: create wsldl installer
              run: scripts/wsldl.cmd
            - name: save artifact
              uses: actions/upload-artifact@v2
              with:
                  name: rootfs
                  path: |
                      build/kareszwsl.tar.gz
                      build/wsldl/
            - name: create env for release
              run: |
                  echo "RELEASE_DATE=$(Get-Date (Get-Date).ToUniversalTime() -UFormat '%Y.%m.%d - %R')" >> $GITHUB_ENV
                  echo "LAST_COMMIT=$(git rev-parse HEAD)" >> $GITHUB_ENV
            - name: test env vars
              run: |
                  echo ${{env.RELEASE_DATE}}
                  echo ${{env.LAST_COMMIT}}
            - name: release
              uses: ncipollo/release-action@v1
              with:
                  allowUpdates: false
                  artifactErrorsFailBuild: true
                  artifacts: |
                      build/kareszwsl.tar.gz
                      build/wsldl.zip
                  commit: ${{env.LAST_COMMIT}}
                  name: ${{env.RELEASE_DATE}}
                  tag: ${{env.RELEASE_DATE}}
                  token: ${{secrets.GITHUB_TOKEN}}
